pipeline {
    agent any
    environment {
        DOCKER_HUB_CREDENTIALS = credentials('dockerhub-credentials')
        SONARQUBE_SERVER = 'SonarQube'
    }
    stages {
        stage('Checkout Code') {
            steps {
                git 'https://github.com/Dobre237/devopsapp.git'
            }
        }
        stage('SonarQube Code Analysis') {
            steps {
                script {
                    withSonarQubeEnv('SonarQube') {
                        sh 'mvn sonar:sonar'
                    }
                }
            }
        }
        stage('Build with Maven') {
            steps {
                sh 'mvn clean install'
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'DOCKER_HUB_CREDENTIALS') {
                        def appImage = docker.build("your-dockerhub-username/webapp")
                        appImage.push('latest')
                    }
                }
            }
        }
        stage('Deploy to Tomcat') {
            steps {
                sshPublisher(
                    publishers: [sshPublisherDesc(
                        configName: 'TomcatServer',
                        transfers: [sshTransfer(
                            sourceFiles: '**/*.war',
                            remoteDirectory: '/opt/tomcat/webapps/'
                        )]
                    )]
                )
            }
        }
    }
}